version: '3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  backend:
    image: ${DOCKER_USERNAME:sergey1l}/taski_backend:latest
    env_file: .env
    depends_on:
      - db
    restart: always

  frontend:
    image: ${DOCKER_USERNAME:sergey1l}/taski_frontend:latest
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  gateway:
    image: ${DOCKER_USERNAME:sergey1l}/taski_gateway:latest
    ports:
      - "8000:80"
    volumes:
      - static:/staticfiles
    depends_on:
      - backend
      - frontend
    restart: always